---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: artifactory
spec:
  releaseName: artifactory
  forceUpgrade: false
  chart:
    repository: https://charts.jfrog.io
    name: artifactory
    version: 9.3.1
  values:
    nameOverride: jfrog
    artifactory:
      name: artifactory
      image:
        repository: docker.bintray.io/jfrog/artifactory-oss
    nginx:
      http:
        internalPort: 8001
        externalPort: 8001
      https:
        enabled: false
